const placeholder=(label,color)=>`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="${color}"/><circle cx="620" cy="100" r="170" fill="white" opacity=".16"/><rect x="170" y="125" width="460" height="250" rx="28" fill="white" opacity=".65"/><text x="400" y="270" text-anchor="middle" font-size="46" font-family="sans-serif" fill="#24483c">${label}</text></svg>`)}`;
let assets=[
 {id:1,name:'互動式電子白板',code:'HKU-113-01482',location:'教學大樓 A棟｜A305教室',uses:47,confirmed:true,image:placeholder('電子白板','#b9d3ca')},
 {id:2,name:'筆記型電腦',code:'HKU-112-00873',location:'行政大樓｜資訊中心',uses:82,confirmed:true,image:placeholder('筆記型電腦','#c6d2d8')},
 {id:3,name:'單眼相機',code:'HKU-111-00326',location:'設計大樓｜器材室 B',uses:31,confirmed:true,image:placeholder('單眼相機','#d5c9bb')},
 {id:4,name:'手持式投影機',code:'HKU-113-01904',location:'教學大樓 B棟｜B202教室',uses:18,confirmed:false,image:placeholder('投影機','#b8c8bd')},
 {id:5,name:'無線麥克風組',code:'HKU-110-00158',location:'學生活動中心｜器材室',uses:29,confirmed:true,image:placeholder('麥克風組','#c9c2ba')},
 {id:6,name:'平板電腦',code:'HKU-113-02117',location:'圖書館｜數位學習區',uses:54,confirmed:true,image:placeholder('平板電腦','#bfd1d0')},
 {id:7,name:'行動音響',code:'HKU-109-00642',location:'學生活動中心｜服務台',uses:11,confirmed:false,image:placeholder('行動音響','#d7c9b7')},
 {id:8,name:'文件掃描器',code:'HKU-112-01139',location:'行政大樓｜教務處',uses:23,confirmed:true,image:placeholder('文件掃描器','#c8d3c4')}
];
let currentView='all';
const grid=document.querySelector('#assetGrid'),search=document.querySelector('#search'),filter=document.querySelector('#locationFilter'),sort=document.querySelector('#sortBy'),dialog=document.querySelector('#editDialog');
function locations(){return [...new Set(assets.map(x=>x.location.split('｜')[0]))]}
function refreshFilters(){const old=filter.value;filter.innerHTML='<option value="">全部位置</option>'+locations().map(x=>`<option>${x}</option>`).join('');filter.value=old}
function visible(){let list=assets.filter(x=>{const q=search.value.trim().toLowerCase();return(!q||x.name.toLowerCase().includes(q)||x.code.toLowerCase().includes(q))&&(!filter.value||x.location.startsWith(filter.value))&&(currentView==='all'||currentView==='frequent'&&x.uses>=40||currentView==='attention'&&!x.confirmed)});if(sort.value==='uses')list.sort((a,b)=>b.uses-a.uses);if(sort.value==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'zh-Hant'));return list}
function render(){const list=visible();grid.innerHTML=list.length?list.map(x=>`<article class="asset-card"><div class="photo"><img src="${x.image}" alt="${x.name}"><span class="status ${x.confirmed?'':'attention'}">${x.confirmed?'✓ 位置已確認':'! 待確認位置'}</span></div><div class="card-body"><div class="card-top"><div><div class="asset-name">${x.name}</div><div class="code">財編 ${x.code}</div></div><button class="dots" data-edit="${x.id}" aria-label="編輯 ${x.name}">•••</button></div><div class="location"><span>⌖</span><div><b>目前位置</b>${x.location}</div></div><div class="card-foot"><div class="uses"><small>累計使用次數</small><strong>${x.uses}</strong> 次</div><button class="use-btn" data-use="${x.id}">＋ 記錄使用</button></div></div></article>`).join(''):'<div class="empty">找不到符合條件的財產</div>';document.querySelector('#resultText').textContent=`顯示 ${list.length} 件財產`;document.querySelector('#totalCount').textContent=assets.length;document.querySelector('#locatedCount').textContent=assets.filter(x=>x.confirmed).length;document.querySelector('#attentionCount').textContent=assets.filter(x=>!x.confirmed).length;document.querySelector('#monthUses').textContent=assets.reduce((n,x)=>n+x.uses,0)}
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function openEditor(item={id:'',name:'',code:'',location:'',image:''}){document.querySelector('#dialogTitle').textContent=item.id?'更新財產資料':'新增財產';['Id','Name','Code','Location','Image'].forEach(k=>document.querySelector('#edit'+k).value=item[k.toLowerCase()]||'');dialog.showModal()}
document.addEventListener('click',e=>{const use=e.target.closest('[data-use]');if(use){assets.find(x=>x.id==use.dataset.use).uses++;render();toast('已新增 1 次使用紀錄')}const edit=e.target.closest('[data-edit]');if(edit)openEditor(assets.find(x=>x.id==edit.dataset.edit));if(e.target.closest('#addBtn'))openEditor();if(e.target.closest('.menu'))document.querySelector('.sidebar').classList.toggle('open');const nav=e.target.closest('.nav-item');if(nav){document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));nav.classList.add('active');currentView=nav.dataset.view;render();document.querySelector('.sidebar').classList.remove('open')}});
document.querySelector('#editForm').addEventListener('submit',e=>{e.preventDefault();const id=+document.querySelector('#editId').value;const data={name:document.querySelector('#editName').value,code:document.querySelector('#editCode').value,location:document.querySelector('#editLocation').value,image:document.querySelector('#editImage').value||placeholder('物品圖片','#c8d4cf')};if(id){Object.assign(assets.find(x=>x.id===id),data,{confirmed:true})}else assets.push({id:Date.now(),...data,uses:0,confirmed:true});dialog.close();refreshFilters();render();toast(id?'財產資料已更新':'已新增財產')});
[search,filter,sort].forEach(el=>el.addEventListener(el===search?'input':'change',render));refreshFilters();render();
